apiVersion: v1
kind: LimitRange # it gonna add these limit ranges to the default namespace if nothing is specified explicitly
metadata:
  name: my-limit-range
  namespace: my-namespace
spec:
  limits: # although if we din't mention the resource block in deployment, it gonna take from this limit-range yaml file
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 200Mi
    default:
      cpu: 200m
      memory: 500Mi
    min:
      cpu: 50m
      memory: 100Mi
    max:
      cpu: 500m
      memory: 1Gi