apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sudhamshapp/reagapp
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx
spec:
  selector: 
    app: nginx
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080        
  type: LoadBalancer

# http://ad3b25753871646488da1b6f23f64538-1609455397.us-west-2.elb.amazonaws.com:8090/webapp/