apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi  # Define the size of the volume
  accessModes:
    - ReadWriteOnce  # Access mode (e.g., ReadWriteOnce, ReadWriteMany, ReadOnlyMany)
  persistentVolumeReclaimPolicy: Retain  # Policy for what happens to the volume after it's released
  storageClassName: standard  # Storage class name (optional)
  hostPath:
    path: /path/to/host/directory  # Path on the host machine
