---
- hosts: localhost
  tasks:
    - name: installation of git
      yum: name=git state=present
    - name: installation of httpd
      yum: name=httpd state=present  



---
- hosts: managed-nodes
  tasks:
    - name: installation of git
      become: true
      yum:
        name: git
        state: latest


---
- hosts: managed-nodes
  tasks:
    - name: Yum repolist for Docker
      become: true
      yum_repository:
        name: docker
        description: yum repository for docker
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no

    - name: Package Installer For Docker
      package:
        name: docker-ce-3:18.09.1-3.el7
        state: present

    - name: Package Installer For Python3 
      package:
        name: python3
        state: present

    - name: Installing python library for the Docker Remote API
      pip:
        name: docker-py

    - name: Start service docker
      service:
        name: docker
        state: started

    - name: Copy Html Code to Controller Node
      copy:
        src: ./webPage/
        dest: /home/Web/

    - name: Create a web container
      docker_container:
        name: web
        image: httpd
        ports:
          - "8080:80"
        volumes:
          - /home/Web:/usr/local/apache2/htdocs/
      register: status

    - debug:
        var: status



---
- hosts: all
  become: true
  tasks:
  - name: installation of tree package
    yum:
      name: tree
      state: present



---
- hosts: all
  become: true
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src:  /opt/tree.yml
      dest: /etc/tree.yml
