---
- hosts: sudhamsh
  tasks:
    - name: installation of httpd
      yum: name=httpd state=present
    - name: copying the host from host
      copy: src=index.html dest=/var/www/html/index.html
    - name: start the httpd server
      service: name=httpd state=started









- name: installation of httpd
  yum: name=httpd state=present
- name: copying the host from host
  copy: src=index.html dest=/var/www/html/index.html
- name: start the httpd server
  service: name=httpd state=started





---
- hosts: all
  become: true
  tasks:  
  - name: Create a directory if it does not exist
    file:
      path: /etc/mars
      state: directory
      mode: '0755'
