# ansible-playbook playbook.yml --tags install_apache
# ansible-playbook playbook.yml --skip-tags start_postgresql
---
- name: Example Playbook with Tags
  hosts: web_servers
  become: true
  tasks:
    - name: Install Apache web server
      package:
        name: apache2
        state: present
      tags:
        - install_apache

    - name: Start Apache service
      service:
        name: apache2
        state: started
      tags:
        - start_apache

    - name: Install PostgreSQL database
      package:
        name: postgresql
        state: present
      tags:
        - install_postgresql

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
      tags:
        - start_postgresql
