---
- hosts: ansible
  tasks:
  - name: building the docker image
    command: docker build -t reagapp:latest .
    args:
      chdir: /opt/docker
  - name: create a tag to push onto dockerhub
    command: docker tag reagapp:latest sudhamshapp/reagapp:latest
  - name: push image onto dockerhub
    command: docker push sudhamshapp/reagapp:latest  
