---
- hosts: localhost
  vars: # can be used this in the entire playbook
    packages: wget, git, tree
  tasks:
    - name: installing the stuff
      yum: name={{packages}} state=present  




---
- hosts: managed-nodes
  vars:
    packages: telnet, tree
  tasks:
    - name: installing the packages the with vars
      become: true
      yum:
        name: "{{packages}}"
        state: present