pipeline {
    agent any

    environment {
        DOCKER_REGISTRY_CREDENTIALS = credentials('docker-registry-credentials') // Define your Docker registry credentials
        IMAGE_NAME = 'my-image'
        IMAGE_VERSION = '1.0'
        BUILD_NUMBER = '123' // You can dynamically generate or pass the build number
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Build your Docker image
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_VERSION} ."
                }
            }
        }

        stage('Tag Docker Image with Build Number') {
            steps {
                script {
                    // Tag the Docker image with the build number
                    sh "docker tag ${IMAGE_NAME}:${IMAGE_VERSION} ${IMAGE_NAME}:${IMAGE_VERSION}.${BUILD_NUMBER}"
                }
            }
        }

        stage('Login to Docker Registry') {
            steps {
                script {
                    // Log in to your Docker registry using credentials
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker-registry-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]) {
                        sh "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} <registry-url>"
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // Push the tagged image to the Docker registry
                    sh "docker push ${IMAGE_NAME}:${IMAGE_VERSION}.${BUILD_NUMBER}"
                }
            }
        }
    }
}
